#!/usr/bin/env python2

'''Hipshot - Simulate long-exposure photography

Usage:
    hipshot <file> [--weight <alpha>]
    hipshot -h | --help
    hipshot -v | --version

Options:
    -w, --weight    Sum frames with the specified weight.
    -h, --help      Print this help.
    -v, --version   Print version information.
'''


import cv
from docopt import docopt
try:
    from os import EX_DATAERR, EX_NOINPUT, EX_USAGE
except ImportError:
    EX_DATAERR, EX_NOINPUT, EX_USAGE = 1, 2, 3
from os.path import exists
from sys import exit, float_info, stderr

from hipshot import cvutils, hipshot


long_version = 'Hipshot ' + hipshot.__version__


if '__main__' in __name__:

    arguments = docopt(__doc__, version=long_version)

    file = arguments['<file>']
    if not exists(file):
        print>>stderr, 'error: file does not exist:', file
        exit(EX_NOINPUT)

    if arguments['--weight']:
        try:
            alpha = float(arguments['<alpha>'])
        except ValueError:
            print>>stderr, 'error: alpha value must be a float'
            exit(EX_USAGE)
    else:
        alpha = 5e-3 / cvutils.num_frames(file)
    if (alpha <= 10.0 * float_info.epsilon or
            alpha >= 1.0 - 10.0 * float_info.epsilon):
        print>>stderr, 'error: alpha value must be between 0 and 1'
        exit(EX_USAGE)

    try:
        cv.NamedWindow('Hipshot', flags=cv.CV_WINDOW_AUTOSIZE)
        print hipshot.merge(file, alpha, display='Hipshot')
    except IOError:
        print>>stderr, 'error: could not read or write file(s)'
        exit(EX_DATAERR)
