#!/usr/bin/env python2

'''Hipshot - Simulate long-exposure photography

Usage:
    hipshot <file> [--weight <alpha>]
    hipshot -h | --help
    hipshot -v | --version

Options:
    -w, --weight    Sum frames with the specified weight.
    -h, --help      Print this help.
    -v, --version   Print version information.
'''


import cv
from docopt import docopt
try:
    from os import EX_DATAERR, EX_NOINPUT, EX_USAGE
except ImportError:
    EX_DATAERR, EX_NOINPUT, EX_USAGE = 1, 2, 3
from os.path import exists
from sys import exit, float_info, stderr

from avena import image, ocv
from hipshot import hipshot


long_version = 'Hipshot ' + hipshot.__version__

_EXT = '.png'


if '__main__' in __name__:

    arguments = docopt(__doc__, version=long_version)

    filename = arguments['<file>']
    if not exists(filename):
        print>>stderr, 'error: file does not exist:', filename
        exit(EX_NOINPUT)

    if arguments['--weight']:
        try:
            alpha = float(arguments['<alpha>'])
        except ValueError:
            print>>stderr, 'error: alpha value must be a float'
            exit(EX_USAGE)
    else:
        alpha = 5e-3 / ocv.num_frames(filename)
    eps = float_info.epsilon
    if alpha <= 10.0 * eps or alpha >= 1.0 - 10.0 * eps:
        print>>stderr, 'error: alpha value must be between 0 and 1'
        exit(EX_USAGE)

    try:
        frames = ocv.get_frames(video_file=filename, as_array=True)
        cv.NamedWindow('Hipshot', flags=cv.CV_WINDOW_AUTOSIZE)
        merged_frames = hipshot.merge(frames, alpha, display='Hipshot')
        print image.save(merged_frames, filename, random=True, ext=_EXT)
    except IOError:
        print>>stderr, 'error: could not read or write file(s)'
        exit(EX_DATAERR)
